const tableData = [
  {
    name: "Tiger Nixon",
    //position: "System Architect",
    store: "Edinburgh",
    age: 61,
    serviceDate: "2011/04/25",
    charge: "$320,800",
  },
  {
    name: "Garrett Winters",
    //position: "Accountant",
    store: "Tokyo",
    age: 63,
    serviceDate: "2011/07/25",
    charge: "$170,750",
  },
  {
    name: "Ashton Cox",
    //position: "Junior Technical Author",
    store: "San Francisco",
    age: 66,
    serviceDate: "2009/01/12",
    charge: "$86,000",
  },
  {
    name: "Cedric Kelly",
    //position: "Senior Javascript Developer",
    store: "Edinburgh",
    age: 22,
    serviceDate: "2012/03/29",
    charge: "$433,060",
  },
  {
    name: "Airi Satou",
    //position: "Accountant",
    store: "Tokyo",
    age: 33,
    serviceDate: "2008/11/28",
    charge: "$162,700",
  },
  {
    name: "Brielle Williamson",
    //position: "Integration Specialist",
    store: "New York",
    age: 61,
    serviceDate: "2012/12/02",
    charge: "$372,000",
  },
  {
    name: "Herrod Chandler",
    //position: "Sales Assistant",
    store: "San Francisco",
    age: 59,
    serviceDate: "2012/08/06",
    charge: "$137,500",
  },
  {
    name: "Rhona Davidson",
    //position: "Integration Specialist",
    store: "Tokyo",
    age: 55,
    serviceDate: "2010/10/14",
    charge: "$327,900",
  },
  {
    name: "Colleen Hurst",
    //position: "Javascript Developer",
    store: "San Francisco",
    age: 39,
    serviceDate: "2009/09/15",
    charge: "$205,500",
  },
  {
    name: "Sonya Frost",
    //position: "Software Engineer",
    store: "Edinburgh",
    age: 23,
    serviceDate: "2008/12/13",
    charge: "$103,600",
  },
  {
    name: "Jena Gaines",
    //position: "store Manager",
    store: "London",
    age: 30,
    serviceDate: "2008/12/19",
    charge: "$90,560",
  },
  {
    name: "Quinn Flynn",
    //position: "Support Lead",
    store: "Edinburgh",
    age: 22,
    serviceDate: "2013/03/03",
    charge: "$342,000",
  },
  {
    name: "Charde Marshall",
    //position: "Regional Director",
    store: "San Francisco",
    age: 36,
    serviceDate: "2008/10/16",
    charge: "$470,600",
  },
  {
    name: "Haley Kennedy",
    //position: "Senior Marketing Designer",
    store: "London",
    age: 43,
    serviceDate: "2012/12/18",
    charge: "$313,500",
  },
  {
    name: "Tatyana Fitzpatrick",
    //position: "Regional Director",
    store: "London",
    age: 19,
    serviceDate: "2010/03/17",
    charge: "$385,750",
  },
  {
    name: "Michael Silva",
    //position: "Marketing Designer",
    store: "London",
    age: 66,
    serviceDate: "2012/11/27",
    charge: "$198,500",
  },
  {
    name: "Paul Byrd",
    //position: "Chief Financial storer (CFO)",
    store: "New York",
    age: 64,
    serviceDate: "2010/06/09",
    charge: "$725,000",
  },
  {
    name: "Gloria Little",
    //position: "Systems Administrator",
    store: "New York",
    age: 59,
    serviceDate: "2009/04/10",
    charge: "$237,500",
  },
  {
    name: "Bradley Greer",
    //position: "Software Engineer",
    store: "London",
    age: 41,
    serviceDate: "2012/10/13",
    charge: "$132,000",
  },
  {
    name: "Dai Rios",
    //position: "Personnel Lead",
    store: "Edinburgh",
    age: 35,
    serviceDate: "2012/09/26",
    charge: "$217,500",
  },
  {
    name: "Jenette Caldwell",
    //position: "Development Lead",
    store: "New York",
    age: 30,
    serviceDate: "2011/09/03",
    charge: "$345,000",
  },
  {
    name: "Yuri Berry",
    //position: "Chief Marketing storer (CMO)",
    store: "New York",
    age: 40,
    serviceDate: "2009/06/25",
    charge: "$675,000",
  },
  {
    name: "Caesar Vance",
    //position: "Pre-Sales Support",
    store: "New York",
    age: 21,
    serviceDate: "2011/12/12",
    charge: "$106,450",
  },
  {
    name: "Doris Wilder",
    //position: "Sales Assistant",
    store: "Sidney",
    age: 23,
    serviceDate: "2010/09/20",
    charge: "$85,600",
  },
  {
    name: "Angelica Ramos",
    //position: "Chief Executive storer (CEO)",
    store: "London",
    age: 47,
    serviceDate: "2009/10/09",
    charge: "$1,200,000",
  },
  {
    name: "Gavin Joyce",
    //position: "Developer",
    store: "Edinburgh",
    age: 42,
    serviceDate: "2010/12/22",
    charge: "$92,575",
  },
  {
    name: "Jennifer Chang",
    //position: "Regional Director",
    store: "Singapore",
    age: 28,
    serviceDate: "2010/11/14",
    charge: "$357,650",
  },
  {
    name: "Brenden Wagner",
    //position: "Software Engineer",
    store: "San Francisco",
    age: 28,
    serviceDate: "2011/06/07",
    charge: "$206,850",
  },
  {
    name: "Fiona Green",
    //position: "Chief Operating storer (COO)",
    store: "San Francisco",
    age: 48,
    serviceDate: "2010/03/11",
    charge: "$850,000",
  },
  {
    name: "Shou Itou",
    //position: "Regional Marketing",
    store: "Tokyo",
    age: 20,
    serviceDate: "2011/08/14",
    charge: "$163,000",
  },
  {
    name: "Michelle House",
    //position: "Integration Specialist",
    store: "Sidney",
    age: 37,
    serviceDate: "2011/06/02",
    charge: "$95,400",
  },
  {
    name: "Suki Burks",
    //position: "Developer",
    store: "London",
    age: 53,
    serviceDate: "2009/10/22",
    charge: "$114,500",
  },
  {
    name: "Prescott Bartlett",
    //position: "Technical Author",
    store: "London",
    age: 27,
    serviceDate: "2011/05/07",
    charge: "$145,000",
  },
  {
    name: "Gavin Cortez",
    //position: "Team Leader",
    store: "San Francisco",
    age: 22,
    serviceDate: "2008/10/26",
    charge: "$235,500",
  },
  {
    name: "Martena Mccray",
    //position: "Post-Sales support",
    store: "Edinburgh",
    age: 46,
    serviceDate: "2011/03/09",
    charge: "$324,050",
  },
  {
    name: "Unity Butler",
    //position: "Marketing Designer",
    store: "San Francisco",
    age: 47,
    serviceDate: "2009/12/09",
    charge: "$85,675",
  },
  {
    name: "Howard Hatfield",
    //position: "store Manager",
    store: "San Francisco",
    age: 51,
    serviceDate: "2008/12/16",
    charge: "$164,500",
  },
  {
    name: "Hope Fuentes",
    //position: "Secretary",
    store: "San Francisco",
    age: 41,
    serviceDate: "2010/02/12",
    charge: "$109,850",
  },
  {
    name: "Vivian Harrell",
    //position: "Financial Controller",
    store: "San Francisco",
    age: 62,
    serviceDate: "2009/02/14",
    charge: "$452,500",
  },
  {
    name: "Timothy Mooney",
    //position: "store Manager",
    store: "London",
    age: 37,
    serviceDate: "2008/12/11",
    charge: "$136,200",
  },
  {
    name: "Jackson Bradshaw",
    //position: "Director",
    store: "New York",
    age: 65,
    serviceDate: "2008/09/26",
    charge: "$645,750",
  },
  {
    name: "Olivia Liang",
    //position: "Support Engineer",
    store: "Singapore",
    age: 64,
    serviceDate: "2011/02/03",
    charge: "$234,500",
  },
  {
    name: "Bruno Nash",
    //position: "Software Engineer",
    store: "London",
    age: 38,
    serviceDate: "2011/05/03",
    charge: "$163,500",
  },
  {
    name: "Sakura Yamamoto",
    //position: "Support Engineer",
    store: "Tokyo",
    age: 37,
    serviceDate: "2009/08/19",
    charge: "$139,575",
  },
  {
    name: "Thor Walton",
    //position: "Developer",
    store: "New York",
    age: 61,
    serviceDate: "2013/08/11",
    charge: "$98,540",
  },
  {
    name: "Finn Camacho",
    //position: "Support Engineer",
    store: "San Francisco",
    age: 47,
    serviceDate: "2009/07/07",
    charge: "$87,500",
  },
  {
    name: "Serge Baldwin",
    //position: "Data Coordinator",
    store: "Singapore",
    age: 64,
    serviceDate: "2012/04/09",
    charge: "$138,575",
  },
  {
    name: "Zenaida Frank",
    //position: "Software Engineer",
    store: "New York",
    age: 63,
    serviceDate: "2010/01/04",
    charge: "$125,250",
  },
  {
    name: "Zorita Serrano",
    //position: "Software Engineer",
    store: "San Francisco",
    age: 56,
    serviceDate: "2012/06/01",
    charge: "$115,000",
  },
  {
    name: "Jennifer Acosta",
    //position: "Junior Javascript Developer",
    store: "Edinburgh",
    age: 43,
    serviceDate: "2013/02/01",
    charge: "$75,650",
  },
  {
    name: "Cara Stevens",
    //position: "Sales Assistant",
    store: "New York",
    age: 46,
    serviceDate: "2011/12/06",
    charge: "$145,600",
  },
  {
    name: "Hermione Butler",
    //position: "Regional Director",
    store: "London",
    age: 47,
    serviceDate: "2011/03/21",
    charge: "$356,250",
  },
  {
    name: "Lael Greer",
    //position: "Systems Administrator",
    store: "London",
    age: 21,
    serviceDate: "2009/02/27",
    charge: "$103,500",
  },
  {
    name: "Jonas Alexander",
    //position: "Developer",
    store: "San Francisco",
    age: 30,
    serviceDate: "2010/07/14",
    charge: "$86,500",
  },
  {
    name: "Shad Decker",
    //position: "Regional Director",
    store: "Edinburgh",
    age: 51,
    serviceDate: "2008/11/13",
    charge: "$183,000",
  },
  {
    name: "Michael Bruce",
    //position: "Javascript Developer",
    store: "Singapore",
    age: 29,
    serviceDate: "2011/06/27",
    charge: "$183,000",
  },
  {
    name: "Donna Snider",
    //position: "Customer Support",
    store: "New York",
    age: 27,
    serviceDate: "2011/01/25",
    charge: "$112,000",
  },
];

const tableColumns = [
  {
    dataField: "name",
    text: "Name",
    sort: true,
  },
  // {
  //   dataField: "//position",
  //   text: "//position",
  //   sort: true,
  // },
  {
    dataField: "store",
    text: "Store",
    sort: true,
  },
  {
    dataField: "age",
    text: "Age",
    sort: true,
  },
  {
    dataField: "serviceDate",
    text: "Service Date",
    sort: true,
  },
  {
    dataField: "charge",
    text: "Charge",
    sort: true,
  },
];

export { tableData, tableColumns };
